spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testredis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Password

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000 #\u8FDE\u63A5\u8D85\u65F6
    jedis:
      pool:
        max-active: 20  #\u6700\u5927\u8FDE\u63A5\u6570
        max-idle: 10    #\u6700\u5927\u7A7A\u95F2\u6570
        min-idle: 0     #\u6700\u5C0F\u7A7A\u95F2\u6570
        max-wait: 10000 #\u963B\u585E\u7B49\u5F85\u65F6\u95F4



mybatis:
  type-aliases-package: com.example.demom.domain
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
